apiVersion: v1
kind: Service
metadata:
  name: monocker-registry-service
  labels:
    app:      monocker
    service:  registry
    type:     service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app:      monocker
    service:  registry