apiVersion: v1
kind: Service
metadata:
  name: monocker-registry-service-dev
  labels:
    app:          monocker
    service:      registry
    type:         service
    environment:  dev
spec:
  type: NodePort
  ports:
  - nodePort:   30123
    port:       5000
    protocol:   TCP
  selector:
    app:      monocker
    service:  registry