swagger: "2.0"
info:
  version: "0.0.1"
  title: Monocker Registry
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

#define routes
paths:
  #============================================================================      
  # models routes
  #============================================================================
  /models:
    x-swagger-router-controller: model_registry
    get:
      description: Returns active models to the caller
      operationId: getModels
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ModelResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      description: Registers 1 or more models
      operationId: registerModels
      parameters:
        - name: models
          description: Array of 1 or more models
          in: body
          required: true
          schema:
            $ref: "#/definitions/models"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  #============================================================================


  #============================================================================      
  # swagger routes
  #============================================================================
  /swagger:
    x-swagger-pipe: swagger_raw
  #============================================================================


definitions:
  #============================================================================      
  # data definitions
  #============================================================================
  model:
    type: object
    properties:
      model_name:
        type: string
      ip_address:
        type: string
      port:
        type: integer

  models:
    type: array
    items:
      $ref: "#/definitions/model"
  #============================================================================


  #============================================================================      
  # responses
  #============================================================================
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  ModelResponse:
    required:
      - models
    properties:
      models:
        $ref: "#/definitions/models"
  #============================================================================
