apiVersion: v1
kind: Service
metadata:
  name: monocker-api-dev-service
  labels:
    app:          monocker
    service:      api
    type:         service
    purpose:      dev
spec:
  type: NodePort
  ports:
  - nodePort:   30112
    port:       8123
    protocol:   TCP
  selector:
    app:      monocker
    service:  api
    purpose:  dev