apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monocker-api.dev.deployment
  labels:
    app:      monocker
    service:  api
    type:     deployment
    purpose:  dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:      monocker
        service:  api
        type:     pod
    spec:
      containers:
        - name:             monocker-api
          image:            randypitcherii/monocker-api
          imagePullPolicy:  Always
          ports:
          - containerPort: 8123
          volumeMounts:
          - mountPath: /mnt/monocker_api
            name: dev-mount
      volumes:
      - name: dev-mount
        hostPath:
          # directory location on host
          path: /mnt/monocker_api
          # this field is optional
          type: Directory