apiVersion: v1
kind: PersistentVolume
metadata:
  name: monocker-registry.pv
  labels:
    app:      monocker
    service:  registry
    type:     persistentVolume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/monocker-registry.pv/
  persistentVolumeReclaimPolicy: Recycle

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monocker-registry.pvc
  labels:
    app:      monocker
    service:  registry
    type:     persistentVolumeClaim
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: monocker-registry.pv